module.exports = {
  apps: [
    {
      name: 'tiktok-ugc-studio',
      script: 'venv/bin/uvicorn',
      args: 'main:app --host 0.0.0.0 --port 8105',
      cwd: __dirname,
      interpreter: 'none',
      env: {
        LLM_API_KEY: process.env.LLM_API_KEY || '',
        LLM_BASE_URL: process.env.LLM_BASE_URL || 'https://api.deepseek.com',
        LLM_MODEL: process.env.LLM_MODEL || 'deepseek-chat',
        WAVESPEED_API_KEY: process.env.WAVESPEED_API_KEY || '',
        FAL_API_KEY: process.env.FAL_API_KEY || process.env.FAL_KEY || '',
        GEMINI_API_KEY: process.env.GEMINI_API_KEY || '',
        MISTRAL_API_KEY: process.env.MISTRAL_API_KEY || '',
        PRODUCT_PORT: '8105',
      },
      max_restarts: 10,
      min_uptime: '10s',
      error_file: '/tmp/pm2-tiktok-ugc-error.log',
      out_file: '/tmp/pm2-tiktok-ugc-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'product-scraper',
      script: '/home/openhands/erp-stack/tiktok-ugc-studio/venv/bin/uvicorn',
      args: 'product.main:app --host 0.0.0.0 --port 8106',
      cwd: '/home/openhands/erp-stack/modules',
      interpreter: 'none',
      env: {
        DATABASE_URL: 'sqlite+aiosqlite:////tmp/scraper.db',
        PYTHONPATH: '/home/openhands/erp-stack/modules',
        PROXY_URL: process.env.PROXY_URL || '',
        PROXY_ENABLED: 'true',
        DATAIMPULSE_PROXY: process.env.DATAIMPULSE_PROXY || '',
      },
      max_restarts: 10,
      min_uptime: '10s',
      error_file: '/tmp/pm2-scraper-error.log',
      out_file: '/tmp/pm2-scraper-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
